# permissions for end users to view duopods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: duopod-operator
    app.kubernetes.io/managed-by: kustomize
  name: duopod-viewer-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - duopods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - duopods/status
  verbs:
  - get
