# permissions for end users to edit duopods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: duopod-operator
    app.kubernetes.io/managed-by: kustomize
  name: duopod-editor-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - duopods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - duopods/status
  verbs:
  - get
